### ISSUE TITLE
Centos 6.9 support for thread affinity

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Java-Thread-Affinity#40]

**Comment by RobAustin** [comment]
BTW While 6.x was first released in 2011, it is still supported by RedHat so we should probably support it which means we need a server or virtual server running it to run builds on. I am not sure it needs it's own teamcity agent.

----

The affinity is only useful if you have isolated CPUs. 
Even if affinity worked, without isolation it can only cause issues.

Never the less we are open to supporting Redhat/Centos 6.x 

-----

However, Krishna’s complaint is that he is not able to switch affinity on.

**Comment by epickrram** [comment]
This is due to upgrading to a newer version of jna (on 01/07/2017) in third-party-bom.

Downgrading will solve the issue - there is no comment as to why the version was upgraded, assuming good practice.

Alternatives are to override the jna artifact version in the project pom, or do some maven magic with dependency hierarchy to allow the version number to be parameterised.

**Comment by RobAustin** [comment]
Could you downgrade it for now and re-release the third-party-bom

**Comment by epickrram** [comment]
released 3.6.1

**Comment by RobAustin** [comment]
thanks
