### ISSUE TITLE
Changed Affinity lock files to make use of file locks which get released on kill -9 

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Java-Thread-Affinity#46]
Affinity locks ( are used to ensure that threads are bound exclusively to a CPU core), we currently use files for this. The problem with using files is that the files are not removed if the process is kill -9'd.

A solution would be to add a lock to the file, locks on files are removed when the process is killed using 'kill -9'

We should ensure that when the  file is created,  it must be created with 'chmod 777' in order that any other process on the machine can later take hold of the lock.

When a lock is taken on the file, remove the contents of the file, and replace it with he PID of the current java process that has just acquired the lock,  so in other words the contents of the file will always contain the last PID that has obtained the lock on the file. [ this is just for human trouble shooting ] 

In the case where the lock file is kill -9'd it wont be possible to remove the contents of the file so it is not possible to alway say the contents of the file is the PID current process . As the process may have been killed.

**Comment by tomshercliff** [comment]
@peter-lawrey - a couple of questions on this as I'm not familiar with how exactly the majority of users are using affinity...
1/ When trying to acquire the lock on a cpu via one of the various acquireLock methods, if we are unable to acquire the lock then the LockCheck.updateCpu method will simply catch the IOException, log a warning ("Failed to update lock file...") and the current thread will continue anyway.  Is this the expected behaviour?
2/ Are we happy to give full read/write/execute permissions to any user on the cpu-xx.lock files (i.e. 'rwxrwxrwx' / chmod 777) as Rob suggests.  Or do we want to restrict only to the current user/group (i.e. chmod 755 or 775) instead?

Cheers,
Tom

**Comment by Allchin** [comment]
HI @peter-lawrey   @tomshercliff 

I got " Unable to acquire lock on CPU 3 "  
when running test  AffinityLockBindMain.java  on my centos 7.

I checked all the configurations :
1.isolcpu and rebooted 
[root@localhost tester]# cat /proc/cmdline 
BOOT_IMAGE=/vmlinuz-3.10.0-514.el7.x86_64 root=/dev/mapper/cl-root ro crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet LANG=zh_CN.UTF-8 isolcpus=1,2,3

2.LD_LIBRARY_PATH
[root@localhost tester]# echo $LD_LIBRARY_PATH
/usr/local/lib

[root@localhost tester]# ls $LD_LIBRARY_PATH
libbitcoinconsensus.a  libbitcoinconsensus.la  libbitcoinconsensus.so  libbitcoinconsensus.so.0  libbitcoinconsensus.so.0.0.0  libCEInternals.so 


What else should I config or check ?

**Comment by dpisklov** [comment]
Check that you have write access to /tmp and there's no preexisting file
/tmp/cpu-3 need by some other user.
Otherwise it would be good to see how do you acquire the lock
