### ISSUE TITLE
Exception when acquire cpu lock

### ISSUE THREAD

**Issue by yujg1992** [OpenHFT/Java-Thread-Affinity#53]
import net.openhft.affinity.AffinityLock;
/*
import vanilla.java.clock.ClockSupport;
import vanilla.java.clock.IClock;
import java.io.IOException;
import java.util.Random;
*/

public class test
{
    public static void main(String[] args)
    {
        AffinityLock al = AffinityLock.acquireLock();
        try {
            new Thread(new SleepRunnable(), "reader").start();
            new Thread(new SleepRunnable(), "writer").start();
            new Thread(new SleepRunnable(), "engine").start();
        } finally {
            al.release();
        }
        System.out.println("\nThe assignment of CPUs is\n" + AffinityLock.dumpLocks());
    }
    private static class SleepRunnable implements Runnable {
        public void run() {
            AffinityLock al = AffinityLock.acquireLock();
            try {
                System.out.println("Hello World...!!");
                Thread.sleep(1000);
            } catch (InterruptedException e) {
            } finally {
                al.release();
            }
        }
    }
}

hello, I test the above code, and I get the exception below

Exception in thread "main" java.lang.IllegalArgumentException: Argument value 0x40000000000 exceeds native capacity (4 bytes) mask=0xffffffff00000000
	at com.sun.jna.IntegerType.setValue(IntegerType.java:92)
	at com.sun.jna.IntegerType.<init>(IntegerType.java:55)
	at com.sun.jna.platform.win32.WinDef$DWORD.<init>(WinDef.java:135)
	at net.openhft.affinity.impl.WindowsJNAAffinity.setAffinity(WindowsJNAAffinity.java:93)
	at net.openhft.affinity.Affinity.setAffinity(Affinity.java:163)
	at net.openhft.affinity.AffinityLock.bind(AffinityLock.java:235)
	at net.openhft.affinity.AffinityLock.assignCurrentThread(AffinityLock.java:203)
	at net.openhft.affinity.LockInventory.acquireLock(LockInventory.java:88)
	at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:173)
	at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:157)
	at net.openhft.affinity.AffinityLock.acquireLock(AffinityLock.java:134)
	at com.phenix.farmer.test.main(test.java:15)

I can't find the reason, please help me solve this problem.

**Comment by dpisklov** [comment]
I don't think Windows is supported for CPU affinity (and it's pointless anyway, running something on Windows is slow enough to see no difference from CPU pinning).
@peter-lawrey do we support Windows for affinity?

**Comment by plusterkopp** [comment]
On 16.11.2019 00:07, Dmitry Pisklov wrote:
> I don't think Windows is supported for CPU affinity (and it's pointless
> anyway, running something on Windows is slow enough to see no difference
> from CPU pinning).
> @peter-lawrey <https://github.com/peter-lawrey> do we support Windows
> for affinity?

actually, it does work. A couple of years ago, I added CPU layout
detection using the windows API with gives CPU masks for cores, sockets,
all caches, NUMA nodes and CPU groups (which on windows overcome the 64
cpu limit).
Affinity is pretty much required if you want to use all CPUs on a large
machine. Out of the box, on a machine with, say 4 sockets and 15 SMT
cores each, you would get 120 threads which means windows creates two
groups of 60 system-wide and puts your app in one of them so that
Runtime.availableProcessors reports only 60 logical CPUs. Actually,
nowadways, even on a cheap two-socket machine, the 64 limit is too small
to reach all 2x18x2 LCPUs. With my affinity fork, I can use all of them.

I don't benefit much from locking to a singe core, but I make good use
of caches by exploiting their masks. This would also work with
first-generation EPYCs with their split L3 caches.  I normally set CPU
masks the correspond to a whole socket or cache, meaning there is more
than just one bit set in the mask.

My fork is a couple of years old and in a detached state. I never merged
new code from your project and I am stuck with Java-8 for that reason.

And yes, due to better cache locality I do see a difference from CPU
pinning.

Actually, I would like to have a nice API under Linux that provides the
same detailed layout information that I get for Windows.

cheers,
  Ralf

**Comment by dpisklov** [comment]
@plusterkopp well looks like doesn't work for everyone - code TS supplied works perfectly for me on my linux machine.

**Comment by JoyRichB** [comment]
從我的iPhone傳送

**Comment by JerryShea** [comment]
Closing as the example code works on my Windows machine
