### ISSUE TITLE
Review the fork with new features and merge as appropriate

### ISSUE THREAD

**Issue by dpisklov** [OpenHFT/Java-Thread-Affinity#61]
As commented by @plusterkopp in #52, he created a [fork](https://github.com/plusterkopp/Java-Thread-Affinity) and added new features - need to review the fork and merge as appropriate

**Comment by plusterkopp** [comment]
Please note this was many years ago and that version needs Java 8 to compile.
I also tried to leave all original Interfaces untouched.
I shall also put some more comments on everything, if needed. 
Anyway, since I never looked back and merged, the two forks must have diverged a lot. But I think I left the original classes largely intact.

**Comment by dpisklov** [comment]
@plusterkopp sure thanks!

**Comment by JerryShea** [comment]
@plusterkopp it looks like this has been forgotten. A number of enhancements have been made to this library since your fork. If there is still a use for this fork (and you are happy to rebase it against current `develop` branch) please let me know and we can review.

**Comment by JerryShea** [comment]
@plusterkopp I will close this. Please re-open if there is still a use for this
