### ISSUE TITLE
TeamCity Java 11 build fails

### ISSUE THREAD

**Issue by JerryShea** [OpenHFT/Java-Thread-Affinity#71]
Relates to #58

**Comment by nicktindall** [comment]
I did some reading on this, firstly I'm not sure what the test is for, but the way it's trying to resolve the bootstrap classpath won't work in Java 9 and beyond. It sounds like the nature of bootstrap classloading has changed significantly since the module system was introduced.

See https://www.oracle.com/java/technologies/javase/9-relnotes.html

> The boot class path has been mostly removed in this release. The java -Xbootclasspath and -Xbootclasspath/p options have been removed. The javac -bootclaspath option can only be used when compiling to JDK 8 or older. The system property sun.boot.class.path has been removed. Deployments that rely on overriding platform classes for testing purposes with -Xbootclasspath/p will need to changed to use the --patch-module option that is documented in JEP 261. The -Xbootclasspath/a option is unchanged.

It sounds like adding classes to `java.lang` isn't going to wash in the module'd future.

**Comment by peter-lawrey** [comment]
This class is only used for `Affinity.isNonForkingAffinityAvailable` so it can determine if affinity should be clearer when threads are created.

This uses functionality written by Mr Bartok in 2014.

**Comment by peter-lawrey** [comment]
We don't need this feature as we use CleaningThread which resets the affinity when started.
